services:
  mock-site:
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/usr/share/nginx/html
      - ../tracker/dist:/usr/share/nginx/html/dist
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://127.0.0.1:80/']
      interval: 5s
      timeout: 5s
      retries: 20
