include:
  - packages/clickhouse/docker-compose.yml
  - packages/api/docker-compose.yml
  - packages/proxy/docker-compose.yml
  - packages/web/docker-compose.yml

services:
  mock-site:
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - ./packages/mock-site:/usr/share/nginx/html
      - ./packages/tracker/dist:/usr/share/nginx/html/dist
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://127.0.0.1:80/']
      interval: 5s
      timeout: 5s
      retries: 20
