include:
  - docker-compose.yml

services:
  mock-site:
    extends:
      file: packages/mock-site/docker-compose.yml
      service: mock-site
    depends_on:
      api:
        condition: service_healthy
