import os
import re

agent_files = [
    'AGENTS.md',
    'packages/api/AGENTS.md',
    'packages/clickhouse/AGENTS.md',
    'packages/e2e/AGENTS.md',
    'packages/mock-site/AGENTS.md',
    'packages/proxy/AGENTS.md',
    'packages/tracker/AGENTS.md',
    'packages/web/AGENTS.md'
]

# We need to build a cleaner parser to pull the sections apart,
# modify them gently without losing existing markdown formatting like **Testing**,
# and put them back.

def parse_and_fix(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    # Translate Georgian text first
    content = content.replace('* როგორ to run tests (commands and steps)', '* How to run tests (commands and steps)')

    # We will just do targeted text replacements to fix the duplicate restrictions issues
    # Mock site:
    if "mock-site" in filepath:
        content = re.sub(r'\s*“Do not edit this file directly”\n\s*Follow project conventions and do not edit generated files manually\.', '', content)
        content = re.sub(r'\s*“Do not modify this directory”\n\s*\* Do not convert this into a single page application or introduce heavy build steps\.', '', content)

    # Web:
    if "web" in filepath:
        content = re.sub(r'\s*\* “Do not modify this directory”\n\s*\* Maintain the existing directory boundaries and responsibilities\.', '', content)

    # Replace any instances where prompts are completely missing (unlikely, but let's be safe)
    if '* Rules for indentation' not in content:
        content = content.replace('#### Coding Conventions\n', '#### Coding Conventions\n* Rules for indentation\n')
    if '* Naming conventions' not in content:
        content = content.replace('#### Coding Conventions\n', '#### Coding Conventions\n* Naming conventions\n')
    if '* Restrictions on libraries that should or should not be used' not in content:
        content = content.replace('#### Coding Conventions\n', '#### Coding Conventions\n* Restrictions on libraries that should or should not be used\n')

    if '* How to build the project' not in content:
        content = content.replace('#### Build & Test Commands\n', '#### Build & Test Commands\n* How to build the project\n')
    if '* How to run tests (commands and steps)' not in content:
        content = content.replace('#### Build & Test Commands\n', '#### Build & Test Commands\n* How to run tests (commands and steps)\n')

    if '* Explanation of key directories' not in content:
        content = content.replace('#### Project Structure\n', '#### Project Structure\n* Explanation of key directories\n')
    if '* Guidance on where to place different types of code' not in content:
        content = content.replace('#### Project Structure\n', '#### Project Structure\n* Guidance on where to place different types of code\n')

    if '* Guardrails such as:' not in content:
        content = content.replace('#### Restrictions\n', '#### Restrictions\n* Guardrails such as:\n')

    # Fix the duplicate nested guardrails issue simply
    content = re.sub(r'(  \* "Do not edit this file directly"\n)(?:\s*\* "Do not edit this file directly"\n)+', r'\1', content)
    content = re.sub(r'(  \* "Do not modify this directory"\n)(?:\s*\* "Do not modify this directory"\n)+', r'\1', content)
    content = re.sub(r'(  \* “Do not edit this file directly”\n)(?:\s*\* “Do not edit this file directly”\n)+', r'\1', content)
    content = re.sub(r'(  \* “Do not modify this directory”\n)(?:\s*\* “Do not modify this directory”\n)+', r'\1', content)

    # Ensure they exist under Restrictions
    if '"Do not edit this file directly"' not in content and '“Do not edit this file directly”' not in content:
         content = content.replace('* Guardrails such as:\n', '* Guardrails such as:\n  * "Do not edit this file directly"\n')
    if '"Do not modify this directory"' not in content and '“Do not modify this directory”' not in content:
         content = content.replace('* Guardrails such as:\n', '* Guardrails such as:\n  * "Do not modify this directory"\n')

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

for filepath in agent_files:
    parse_and_fix(filepath)

# Now fix README files
readme_files = [
    'README.md',
    'packages/api/README.md',
    'packages/clickhouse/README.md',
    'packages/e2e/README.md',
    'packages/mock-site/README.md',
    'packages/proxy/README.md',
    'packages/tracker/README.md',
    'packages/web/README.md'
]

replacement_contributing = """## Contributing

Please read the `AGENTS.md` files located in the root directory and inside each package's directory for coding conventions, test execution commands, project structure details, and prohibited patterns. The AI rules outlined in `AGENTS.md` must be followed when contributing to the repository.
"""

for filepath in readme_files:
    if not os.path.exists(filepath):
        continue

    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    if '## Contributing' in content:
        content = re.sub(r'## Contributing.*', replacement_contributing, content, flags=re.DOTALL)
    else:
        content += '\n' + replacement_contributing

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
