services:
  web:
    build:
      context: ../..
      dockerfile: packages/web/Dockerfile
    environment:
      - VITE_API_ENDPOINT=${VITE_API_ENDPOINT:-http://localhost:3001}
      - VITE_PROXY_ENDPOINT=${VITE_PROXY_ENDPOINT:-http://localhost:3002}
      - PORT=3000
    ports:
      - '3000:3000'
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://127.0.0.1:3000/']
      interval: 5s
      timeout: 5s
      retries: 20
