import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const isGraphqlFile = (file) => file.endsWith('.graphql');

async function readGraphqlDir(dir) {
  const files = await readdir(dir);
  return Promise.all(
    files.filter(isGraphqlFile).map(async (file) => {
      const content = await readFile(join(dir, file), 'utf8');
      return content;
    })
  );
}

async function main() {
  const schemaDir = join(__dirname, '../src/graphql/schema');
  const typeDir = join(schemaDir, 'type');

  const rootFiles = await readGraphqlDir(schemaDir);
  const typeFiles = await readGraphqlDir(typeDir);

  const allTypeDefs = [...rootFiles, ...typeFiles];

  const generatedDir = join(__dirname, '../src/graphql/schema/__generated__');
  await mkdir(generatedDir, { recursive: true });

  const tsContent = `// Auto-generated by generate-schema.js
export const typeDefs = [
${allTypeDefs.map((def) => '  `' + def.replace(/`/g, '\\`') + '`').join(',\n')}
];
`;

  await writeFile(join(generatedDir, 'typeDefs.ts'), tsContent);
  console.log('Successfully generated typeDefs.ts');
}

main().catch(console.error);
