CREATE TABLE IF NOT EXISTS lightscope.pv_raw (
    event_id String,
    tenant_id UInt64,
    site_name LowCardinality(String),
    url String,
    url_hash UInt64 MATERIALIZED cityHash64(url),
    event_time DateTime,
    user_id String,
    visit_id String,
    visitor_id String,
    domain String,
    domain_hash UInt64 MATERIALIZED cityHash64(domain),
    referrer String,
    referrer_hash UInt64 MATERIALIZED cityHash64(referrer),
    device LowCardinality(String),
    device_type LowCardinality(String),
    device_vendor LowCardinality(String),
    os LowCardinality(String),
    os_version String,
    app LowCardinality(String),
    app_type LowCardinality(String),
    app_version String,
    age LowCardinality(String),
    gender LowCardinality(String),
    geo_continent LowCardinality(String),
    geo_country LowCardinality(String),
    geo_subdivision LowCardinality(String),
    geo_city LowCardinality(String),
    query_params Map(String, String),
    utm_source LowCardinality(String),
    utm_medium LowCardinality(String),
    utm_campaign LowCardinality(String),
    language LowCardinality(String),
    engagement_time UInt32 DEFAULT 0,
    created_at DateTime DEFAULT now()
) ENGINE = Null;
