// Auto-generated by generate-schema.js
export const typeDefs = [
  `enum AggregationUnit {
  TOTAL
  AUTO
  MINUTE
  HOUR
  DAY
  WEEK
  MONTH
  YEAR
}

enum Metric {
  VISITS_VIEWS
  VISITORS_VIEWS
  USERS_VIEWS
  ENGAGEMENT_TIME
}

enum CategoryName {
  AGE
  APP_TYPE
  APP
  DEVICE_TYPE
  DEVICE_VENDOR
  DEVICE
  GENDER
  REFERRER
  GEO_CONTINENT
  GEO_SUBDIVISION
  GEO_COUNTRY
  GEO_CITY
}

enum Order {
  ASC
  DESC
}
`,
  `input AggregationInput {
  unit: AggregationUnit!
  """
  If unit is not AUTO or Total, specifies the interval for aggregation.
  """
  interval: Int
}

type Aggregation {
  unit: AggregationUnit!
  """
  If unit is not AUTO or Total, specifies the interval for aggregation.
  """
  interval: Int
}

input CategoryInput {
  name: CategoryName!
  value: String!
}

type Category {
  name: CategoryName!
  value: String!
}

input SortInput {
  category: CategoryInput
  order: Order!
}

type Sort {
  category: Category
  order: Order!
}

input ArticleFilterInput {
  includeUrls: [String!]
  excludeUrls: [String!]
  title: String
  includeTypes: [String!]
  excludeTypes: [String!]
  description: String
  includeSiteNames: [String!]
  excludeSiteNames: [String!]
  includeLocales: [String!]
  excludeLocales: [String!]
  publishedTimeBefore: DateTime
  publishedTimeAfter: DateTime
  modifiedTimeBefore: DateTime
  modifiedTimeAfter: DateTime
  expirationTimeBefore: DateTime
  expirationTimeAfter: DateTime
  # Each inner array represents a set of authors where at least one author must be present (logical OR) while outer array represents sets that must all be satisfied (logical AND).
  includeAuthors: [[String!]]
  # Each inner array represents a set of authors where at least one author must be present (logical OR) while outer array represents sets that must all be satisfied (logical AND).
  excludeAuthors: [[String!]]
  includeSections: [String!]
  excludeSections: [String!]
  # Each inner array represents a set of tags where at least one tag must be present (logical OR) while outer array represents sets that must all be satisfied (logical AND).
  includeTags: [[String!]]
  # Each inner array represents a set of tags where at least one tag must be present (logical OR) while outer array represents sets that must all be satisfied (logical AND).
  excludeTags: [[String!]]
}

type ArticleFilter {
  includeUrls: [String!]
  excludeUrls: [String!]
  title: String
  includeTypes: [String!]
  excludeTypes: [String!]
  description: String
  includeSiteNames: [String!]
  excludeSiteNames: [String!]
  includeLocales: [String!]
  excludeLocales: [String!]
  publishedTimeBefore: DateTime
  publishedTimeAfter: DateTime
  modifiedTimeBefore: DateTime
  modifiedTimeAfter: DateTime
  expirationTimeBefore: DateTime
  expirationTimeAfter: DateTime
  # Each inner array represents a set of authors where at least one author must be present (logical OR) while outer array represents sets that must all be satisfied (logical AND).
  includeAuthors: [[String!]]
  # Each inner array represents a set of authors where at least one author must be present (logical OR) while outer array represents sets that must all be satisfied (logical AND).
  excludeAuthors: [[String!]]
  includeSections: [String!]
  excludeSections: [String!]
  # Each inner array represents a set of tags where at least one tag must be present (logical OR) while outer array represents sets that must all be satisfied (logical AND).
  includeTags: [[String!]]
  # Each inner array represents a set of tags where at least one tag must be present (logical OR) while outer array represents sets that must all be satisfied (logical AND).
  excludeTags: [[String!]]
}
`,
  `type Query {
  article(url: String!): Article
  rank(
    startDate: DateTime!
    endDate: DateTime!
    articleFilter: ArticleFilterInput
    order: Order = DESC
    limit: Int = 100
    page: Int = 1
    metric: Metric = VISITS_VIEWS
  ): Rank
  trend(
    startDate: DateTime!
    endDate: DateTime!
    articleFilter: ArticleFilterInput
    aggregation: AggregationInput = { unit: AUTO }
    limit: Int = 100
    page: Int = 1
    metric: Metric = VISITS_VIEWS
  ): Trend
}
`,
  `scalar DateTime
`,
  `type Article {
  url: String!
  title: String
  type: String
  image: String
  description: String
  siteName: String!
  locale: String
  publishedTime: DateTime
  modifiedTime: DateTime
  expirationTime: DateTime
  authors: [String!]!
  section: String
  tags: [String!]!
  analytics(
    startDate: DateTime!
    endDate: DateTime!
    aggregation: AggregationInput = { unit: AUTO }
    limit: Int = 100
    page: Int = 1
    metric: Metric = VISITS_VIEWS
  ): ArticleAnalytics
}

type ArticleAnalyticsParameters {
  startDate: DateTime!
  endDate: DateTime!
  aggregation: Aggregation!
  limit: Int!
  page: Int!
  siteName: String!
  url: String!
  metric: Metric!
}

type ArticleAnalytics {
  parameters: ArticleAnalyticsParameters!
  analytics: [Analytics!]
  analyticsAge: [AnalyticsAge!]
  analyticsApp: [AnalyticsApp!]
  analyticsDevice: [AnalyticsDevice!]
  analyticsGender: [AnalyticsGender!]
  analyticsGeo: [AnalyticsGeo!]
  analyticsReferrer: [AnalyticsReferrer!]
  analyticsUtm: [AnalyticsUtm!]
}

interface AnalyticsBase {
  date: DateTime!
  value: Int!
}

type Analytics implements AnalyticsBase {
  date: DateTime!
  value: Int!
}

type AnalyticsAge implements AnalyticsBase {
  date: DateTime!
  value: Int!
  age: String
}

type AnalyticsApp implements AnalyticsBase {
  date: DateTime!
  value: Int!
  appType: String
  app: String
}

type AnalyticsDevice implements AnalyticsBase {
  date: DateTime!
  value: Int!
  deviceType: String
  deviceVendor: String
  device: String
}

type AnalyticsGender implements AnalyticsBase {
  date: DateTime!
  value: Int!
  gender: String
}

type AnalyticsGeo implements AnalyticsBase {
  date: DateTime!
  value: Int!
  continent: String
  subdivision: String
  country: String
  city: String
}

type AnalyticsReferrer implements AnalyticsBase {
  date: DateTime!
  value: Int!
  domain: String
  referrer: String
}

type AnalyticsUtm implements AnalyticsBase {
  date: DateTime!
  value: Int!
  source: String
  medium: String
  campaign: String
}
`,
  `type Rank {
  total: Int!
  categoryAge(includeAges: [String!], excludeAges: [String!]): [RankAnalytics!]
  categoryApp(
    includeAppTypes: [String!]
    excludeAppTypes: [String!]
    includeApps: [String!]
    excludeApps: [String!]
  ): [RankAnalytics!]
  categoryDevice(
    includeDeviceTypes: [String!]
    excludeDeviceTypes: [String!]
    includeDeviceVendors: [String!]
    excludeDeviceVendors: [String!]
    includeDevices: [String!]
    excludeDevices: [String!]
  ): [RankAnalytics!]
  categoryGender(includeGenders: [String!], excludeGenders: [String!]): [RankAnalytics!]
  categoryGeo(
    includeContinents: [String!]
    excludeContinents: [String!]
    includeSubdivisions: [String!]
    excludeSubdivisions: [String!]
    includeCountries: [String!]
    excludeCountries: [String!]
    includeCities: [String!]
    excludeCities: [String!]
  ): [RankAnalytics!]
  categoryReferrer(
    includeDomains: [String!]
    excludeDomains: [String!]
    includeReferrers: [String!]
    excludeReferrers: [String!]
  ): [RankAnalytics!]
  categoryUtm(
    includeSources: [String!]
    excludeSources: [String!]
    includeMediums: [String!]
    excludeMediums: [String!]
    includeCampaigns: [String!]
    excludeCampaigns: [String!]
  ): [RankAnalytics!]
  articles: [RankAnalytics!]
  parameters: RankParameters!
}

type RankParameters {
  startDate: DateTime!
  endDate: DateTime!
  articleFilter: ArticleFilter
  order: Order!
  limit: Int!
  page: Int!
  metric: Metric!
}

interface RankAnalyticsBase {
  index: Int!
  value: Int!
  url: String!
  article: Article
}

type RankAnalytics implements RankAnalyticsBase {
  index: Int!
  value: Int!
  url: String!
  article: Article
}
`,
  `type Trend {
  total: [TrendAnalytics!]!
  categoryAge(top: Int = 10, includeAges: [String!], excludeAges: [String!]): [TrendAnalyticsAge!]
  categoryApp(
    top: Int = 10
    includeAppTypes: [String!]
    excludeAppTypes: [String!]
    includeApps: [String!]
    excludeApps: [String!]
  ): [TrendAnalyticsApp!]
  categoryDevice(
    top: Int = 10
    includeDeviceTypes: [String!]
    excludeDeviceTypes: [String!]
    includeDeviceVendors: [String!]
    excludeDeviceVendors: [String!]
    includeDevices: [String!]
    excludeDevices: [String!]
  ): [TrendAnalyticsDevice!]
  categoryGender(
    top: Int = 10
    includeGenders: [String!]
    excludeGenders: [String!]
  ): [TrendAnalyticsGender!]
  categoryGeo(
    top: Int = 10
    includeContinents: [String!]
    excludeContinents: [String!]
    includeSubdivisions: [String!]
    excludeSubdivisions: [String!]
    includeCountries: [String!]
    excludeCountries: [String!]
    includeCities: [String!]
    excludeCities: [String!]
  ): [TrendAnalyticsGeo!]
  categoryReferrer(
    top: Int = 10
    includeDomains: [String!]
    excludeDomains: [String!]
    includeReferrers: [String!]
    excludeReferrers: [String!]
  ): [TrendAnalyticsReferrer!]
  categoryUtm(
    top: Int = 10
    includeSources: [String!]
    excludeSources: [String!]
    includeMediums: [String!]
    excludeMediums: [String!]
    includeCampaigns: [String!]
    excludeCampaigns: [String!]
  ): [TrendAnalyticsUtm!]
  articles(top: Int = 10): [TrendAnalyticsArticle!]
  parameters: TrendParameters!
}

type TrendParameters {
  startDate: DateTime!
  endDate: DateTime!
  articleFilter: ArticleFilter
  aggregation: Aggregation!
  limit: Int!
  page: Int!
  metric: Metric!
}

interface TrendAnalyticsBase {
  date: DateTime!
  value: Int!
  url: String
  article: Article
}

type TrendAnalytics implements TrendAnalyticsBase {
  date: DateTime!
  value: Int!
  url: String
  article: Article
}

type TrendAnalyticsAge implements TrendAnalyticsBase {
  date: DateTime!
  value: Int!
  age: String
  url: String!
  article: Article
}

type TrendAnalyticsApp implements TrendAnalyticsBase {
  date: DateTime!
  value: Int!
  appType: String
  app: String
  url: String!
  article: Article
}

type TrendAnalyticsDevice implements TrendAnalyticsBase {
  date: DateTime!
  value: Int!
  deviceType: String
  deviceVendor: String
  device: String
  url: String!
  article: Article
}

type TrendAnalyticsGender implements TrendAnalyticsBase {
  date: DateTime!
  value: Int!
  gender: String
  url: String!
  article: Article
}

type TrendAnalyticsReferrer implements TrendAnalyticsBase {
  date: DateTime!
  value: Int!
  domain: String
  referrer: String
  url: String!
  article: Article
}

type TrendAnalyticsGeo implements TrendAnalyticsBase {
  date: DateTime!
  value: Int!
  continent: String
  subdivision: String
  country: String
  city: String
  url: String!
  article: Article
}

type TrendAnalyticsArticle implements TrendAnalyticsBase {
  date: DateTime!
  value: Int!
  url: String!
  article: Article
}

type TrendAnalyticsUtm implements TrendAnalyticsBase {
  date: DateTime!
  value: Int!
  source: String
  medium: String
  campaign: String
  url: String!
  article: Article
}
`
];
