import { test, expect } from '@playwright/test';
import { generatePayload, generateMinimalPayload } from '../utils/generator';
import { UAParser } from 'ua-parser-js';

test.describe('Data Generator Logic Verification', () => {
  test('generatePayload should create a valid full payload structure', async () => {
    const payload = generatePayload();
    expect(payload.event_id).toBeDefined();
    expect(payload.user_agent).toBeDefined();
    // IP is not generated by the script, handled by API

    // Check consistency between UA and OS/Browser
    const uaParser = new UAParser(payload.user_agent);
    const result = uaParser.getResult();

    // If ua-parser-js can detect OS, it should match our payload
    if (result.os.name) {
      expect(payload.os).toBe(result.os.name);
    }
  });

  test('generateMinimalPayload should create a payload with required fields', async () => {
    const payload = generateMinimalPayload();
    expect(payload.event_id).toBeDefined();
    expect(payload.url).toBeDefined();
    expect(payload.user_agent).toBeDefined();
  });

  test('generatePayload should allow overrides', async () => {
    const customUA =
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
    const payload = generatePayload({ user_agent: customUA });

    expect(payload.user_agent).toBe(customUA);
    expect(payload.os).toBe('macOS');
    expect(payload.app).toBe('Chrome');
  });
});
