import { UAParser } from 'ua-parser-js';
import { describe, expect, test } from 'vitest';
import { generateMinimalPayload, generatePayload } from './generator';

describe('Data Generator Logic Verification', () => {
  test('generatePayload should create a valid full payload structure', () => {
    const payload = generatePayload();
    expect(payload.event_id).toBeDefined();
    expect(payload.user_agent).toBeDefined();
    // IP is not generated by the script, handled by API

    // Check consistency between UA and OS/Browser
    const uaParser = new UAParser(payload.user_agent);
    const result = uaParser.getResult();

    // If ua-parser-js can detect OS, it should match our payload
    if (result.os.name) {
      expect(payload.os).toBe(result.os.name);
    }
  });

  test('generateMinimalPayload should create a payload with required fields', () => {
    const payload = generateMinimalPayload();
    expect(payload.event_id).toBeDefined();
    expect(payload.url).toBeDefined();
    expect(payload.user_agent).toBeDefined();
  });

  test('generatePayload should allow overrides', () => {
    const customUA =
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
    const payload = generatePayload({ user_agent: customUA });

    expect(payload.user_agent).toBe(customUA);

    const uaParser = new UAParser(customUA);
    expect(payload.os).toBe(uaParser.getOS().name);
    expect(payload.app).toBe('Chrome');
  });
});
