name: CI & E2E

on:
  pull_request:
    branches: ['main']
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**/*.md'
      - '**/.gitignore'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node and pnpm
        uses: ./.github/actions/setup

      - name: Run format:check
        run: pnpm run format:check

      - name: Run lint
        run: pnpm run lint

      - name: Run build
        run: pnpm run build

      - name: Run test
        run: pnpm run test
        env:
          JWT_SECRET: ci-test-secret-do-not-use-in-prod

      - name: Get Playwright version
        id: playwright-version
        run: echo "VERSION=$(pnpm --filter @lightscope-ce/e2e exec playwright --version | awk '{print $2}')" >> $GITHUB_ENV

      - name: Install Playwright Browsers
        run: pnpm --filter @lightscope-ce/e2e exec playwright install --with-deps

      - name: Run E2E tests
        run: pnpm run test:e2e
        env:
          JWT_SECRET: ci-test-secret-do-not-use-in-prod
