name: Integration Tests

on:
  pull_request:
    branches: ['main']
    types: [opened, synchronize, reopened]

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node and pnpm
        uses: ./.github/actions/setup

      - name: Run integration tests
        run: pnpm run test:integration
